rootProject.name = "alexzubarev007"
include("lab1")
include("lab2")
include("lab2:Application")
include("lab2:Domain")
include("lab2:Infrastructure")
include("lab2:Application.Abstractions")
include("lab2:Application.Contracts")
include("lab2:Presentation")
include("lab3")
include("lab3:Application")
include("lab3:Domain")
include("lab3:Infrastructure")
include("lab3:Application.Abstractions")
include("lab3:Application.Contracts")
include("lab3:Presentation")