spring:
  main:
    web-application-type: none
  rabbitmq:
    host: ${BANK_RABBIT_HOST:localhost}
    port: ${BANK_RABBIT_PORT:5672}
    username: ${BANK_RABBIT_USER:guest}
    password: ${BANK_RABBIT_PASSWORD:guest}
    queues:
      rates: rates
      requests: rates_request
rates:
  publish-interval: ${RATES_PUBLISH_INTERVAL:10s}
