spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/banks_lab
    username: banks_user
    password: banks_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queues:
      rates: "rates"
      requests: "rates_request"
server:
  port: 8080