spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/banks_lab
    username: banks_user
    password: banks_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true